---
title: "Research Resources"
draft: false
class: "402"

---

# CSUF Library Resources

[CSUF Library Public Health Research Guide](https://libraryguides.fullerton.edu/publichealth)

# Effective Research Presentation

[Research-Guidance.pdf](../../../attachments/Research-Guidance.pdf)
# Some Notes on Sources

> [!success] Reliable non-academic or non-peer reviewed sources
> [KFF](https://www.kff.org/)
>  [Guttmacher Institute](https://www.guttmacher.org/)
>  [Commonwealth Fund](https://www.commonwealthfund.org/)
>  [Urban Institute](https://www.urban.org/)
>  [Millbank Memorial Fund](https://www.milbank.org/)
>  [Health Affairs Forefront](https://www.healthaffairs.org/forefront) Do not confuse this with *Health Affairs* which is a peer-reviewed academic publication.  Forefront is a policy commentary and analysis publication.
>  [STAT News](https://www.statnews.com/) This is a reputable journalism site for health-related news.
>  [KFF Health News](https://kffhealthnews.org/)This is KFF's news publication.


> [!caution] Caution
> US government sources since January 2025.  You should verify this information against academic and scientific peer-reviewed literature.
> 
> Law and policy articles and discussions older than 2020.  It is highly likely that these will not be relevant and may be out-of-date.
> 
> Check the accuracy of any law and policy material as US law has been changing rapidly since January 2025.  Something published in 2024 may no longer be relevant!
> 
> ### Policy Institutes and Journals with Particular Ideological Lenses
> You are encouraged to use high-quality non-governmental sources such as policy institutes, foundations, and health system organizations. These sources are especially valuable for understanding system structure, incentives, governance, and implementation. When using them, focus on how evidence is used to support claims, and be explicit about assumptions or perspectives.
> 	
> 	[Brookings Institution](https://www.brookings.edu/)
> 	[Center for American Progress](https://www.americanprogress.org/)
> 	[American Enterprise Institute](https://www.aei.org/)
> 	[Jacobin](https://jacobin.com/) This magazine is best used for analysis of structure, **not** causal relationships.



> [!danger] Do not use
> Sources published in journals on [Beall's List](https://beallslist.net/) or the [Predatory Journals List](https://www.predatoryjournals.org/the-list/journals).
> 
> Do not use articles or materials that are focused on health care systems or public health outside the United States. Your project is to focus entirely on the US health care system.
> 
> Press releases
> Materials generated by for-profit entitites








