project:
  type: website

website:
  title: "Professor Smith's Classes"
  navbar:
    background: primary
    search: true
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: PUBH_115/pubh115.qmd
        text: PUBH 115
      - href: PUBH_402/pubh402.qmd
        text: PUBH 402
  sidebar:
    style: floating
    search: true
    contents:
      - section: "PUBH 115"
        contents:
          - text: "Welcome"
            href: PUBH_115/pubh115.qmd
      - section: "PUBH 402"
        contents:
          - text: "Welcome"
            href: PUBH_402/pubh402.qmd

format:
  html:
    theme:
      - sandstone
    css: styles.css
    toc: true



