---
title: "Course Description and Objectives"
date: "2026-06-17"
draft: false
class: "115"
categories: "syllabus"

---
# Course Description

How environmental and safety hazards influence public health and sustainability. Multiple perspectives on water, air, and solid waste pollution, sustainability and public safety issues.

This class is focused on providing you an introduction to the relationship between the environment and health; an introduction to environmental health; and, most importantly, an opportunity for you to reflect on your own values, learning, and goals in the context of your existence and the planet that you live on.

---

# General Education

This course meets the requirements of Area E – Lifelong Learning.

---

# Prerequisites

None.

---

# Course Modality

Asynchronous Online

---

# Course Student Learning Outcomes (SLOs)

- Further their own critical self-understanding and acquire the knowledge, skills, and attitudes necessary to engage and reflect in learning and self-development practices.
- Develop strategies to be integrated physiological, socio-cultural, and psychological beings to promote a holistic awareness of lifelong learning throughout their lives.
- Develop themselves as responsible citizens, employees and employers, family members, and members of the global society.
- Actively apply and participate in developing a lifelong commitment to health for both personal well-being (such as physical, financial, emotional, intellectual, spiritual, social/interpersonal, and/or environmental aspects) and societal responsibility.
- Discuss concepts of sustainability associated with natural resources and human population.
- Explore people's attitudes and motivations to change consumptive practices to preserve natural resources.
- Characterize the health outcomes of exposure to environmental pollutants, including air, water, and food.
- Understand the importance of safety in protecting the public and workers from various hazards at home and workplaces.
- Review careers available in environmental health and safety.

